/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CommuteDays = () => {
  const days = ["M", "T", "W", "T", "F", "S", "S"];

  return (
    <div className="self-stretch mt-20 max-md:mt-10 max-md:max-w-full">
      <h2 className="self-start text-3xl font-medium text-black text-opacity-80">
        Commute Days
      </h2>
      <div className="flex flex-wrap gap-5 justify-between mt-12 text-4xl text-center whitespace-nowrap max-md:mt-10">
        {days.map((day, index) => (
          <button
            key={day}
            className={`px-10 pt-7 pb-14 rounded-full border border-emerald-500 border-solid h-[108px] w-[108px] max-md:px-5 ${
              index === 1 || index > 3
                ? "text-white bg-emerald-500"
                : "text-emerald-500 bg-stone-50"
            }`}
            aria-label={`Select ${day} as commute day`}
          >
            {day}
          </button>
        ))}
      </div>
    </div>
  );
};

export default CommuteDays;
