/**
 * This code was generated by Builder.io.
 */
import React from "react";

const InfoCard = ({ imageSrc, altText, description }) => {
  return (
    <div className="flex gap-5 items-start mt-7 max-md:mr-0.5">
      <img
        loading="lazy"
        src={imageSrc}
        alt={altText}
        className="object-contain shrink-0 mt-3 aspect-[0.75] w-[52px]"
      />
      <div className="w-[259px]">
        <br />
        {description}
      </div>
    </div>
  );
};

export default InfoCard;
