/**
 * This code was generated by Builder.io.
 */
import React from "react";

const NameInput = () => {
  return (
    <div>
      <label
        htmlFor="name"
        className="mt-14 text-3xl font-medium text-black text-opacity-80 max-md:mt-10"
      >
        Name
      </label>
      <input
        type="text"
        id="name"
        className="flex shrink-0 mt-6 max-w-full border border-emerald-500 border-solid bg-white bg-opacity-80 h-[65px] rounded-[30px] w-[506px]"
        aria-label="Enter your name"
      />
    </div>
  );
};

export default NameInput;
