/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Sidebar from "./Sidebar";
import WelcomeForm from "./WelcomeForm";

const PlanetShare = () => {
  return (
    <div className="overflow-hidden pr-20 bg-stone-50 max-md:pr-5">
      <div className="flex gap-5 max-md:flex-col">
        <Sidebar />
        <WelcomeForm />
      </div>
    </div>
  );
};

export default PlanetShare;
