/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchBar = () => {
  return (
    <div className="flex gap-3 self-start p-3.5 mt-16 text-xl whitespace-nowrap rounded-xl border border-white border-solid bg-white bg-opacity-10 max-md:mt-10">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/f9852a29d8ee54a9c40ecc34630b15929f33061406897f6b987a3aa8ef31b319?placeholderIfAbsent=true&apiKey=fbe643ad95e8457eb11c897a1f64c686"
        alt=""
        className="object-contain shrink-0 self-start aspect-square w-[18px]"
      />
      <span className="basis-auto">Search</span>
    </div>
  );
};

export default SearchBar;
