/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";
import LocationInput from "./LocationInput";
import VehicleType from "./VehicleType";
import InfoCard from "./InfoCard";

const Sidebar = () => {
  return (
    <aside className="flex flex-col w-[36%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col px-11 pb-14 mx-auto w-full text-2xl font-medium text-white bg-teal-800 max-md:px-5 max-md:mt-10">
        <h1 className="self-start text-5xl text-center max-md:text-4xl">
          <br />
          PlanetShare
          <br />
        </h1>
        <p className="mt-16 w-[259px] max-md:mt-10">
          <br />A carbon footprint networking platform
        </p>
        <SearchBar />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b8c5138f4406e365f714429769a6ef4b0084d68bcf85467ac70af2e431c0cb7b?placeholderIfAbsent=true&apiKey=fbe643ad95e8457eb11c897a1f64c686"
          alt=""
          className="object-contain self-start mt-11 w-full max-md:mt-10"
        />
        <h2 className="self-start mt-3.5 text-2xl font-bold">I want...</h2>
        <LocationInput label="Pickup within" />
        <LocationInput label="Drop-off within" />
        <LocationInput label="Departure time within" />
        <VehicleType />
        <InfoCard
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/bb46c1afc836cd72ef3edc03418e4b050e6a38f99c04cc433eaa392033697b7e?placeholderIfAbsent=true&apiKey=fbe643ad95e8457eb11c897a1f64c686"
          altText="Carbon footprint info"
          description="A carbon footprint networking platform"
        />
        <InfoCard
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/c0e7b1f389d37ca0e30dea6eaad89152f76509a13b45157c204b61bba2823236?placeholderIfAbsent=true&apiKey=fbe643ad95e8457eb11c897a1f64c686"
          altText="Networking info"
          description="A carbon footprint networking platform"
        />
        <InfoCard
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/c0e7b1f389d37ca0e30dea6eaad89152f76509a13b45157c204b61bba2823236?placeholderIfAbsent=true&apiKey=fbe643ad95e8457eb11c897a1f64c686"
          altText="Platform info"
          description="A carbon footprint networking platform"
        />
        <InfoCard
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/c0e7b1f389d37ca0e30dea6eaad89152f76509a13b45157c204b61bba2823236?placeholderIfAbsent=true&apiKey=fbe643ad95e8457eb11c897a1f64c686"
          altText="Additional info"
          description="A carbon footprint networking platform"
        />
      </div>
    </aside>
  );
};

export default Sidebar;
