/**
 * This code was generated by Builder.io.
 */
import React from "react";


const TimeInput = ({ label }) => {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow text-3xl font-medium text-black text-opacity-80 max-md:mt-10">
        <label
          htmlFor={`${label.toLowerCase().replace(/\s+/g, "-")}`}
          className="self-start"
        >
          {label}
        </label>
        <input
          type="time"
          id={`${label.toLowerCase().replace(/\s+/g, "-")}`}
          className="flex shrink-0 mt-6 border border-emerald-500 border-solid bg-white bg-opacity-80 h-[65px] rounded-[30px]"
          aria-label={`Select ${label.toLowerCase()}`}
        />
      </div>
    </div>
  );
};

export default TimeInput;
