/**
 * This code was generated by Builder.io.
 */
import React from "react";

const VehicleType = () => {
  return (
    <>
      <h2 className="self-start mt-10 text-2xl font-bold">Vehicle Type</h2>
      <select
        className="flex shrink-0 mt-3 max-w-full h-10 rounded-xl border border-white border-solid bg-white bg-opacity-10 w-[272px]"
        aria-label="Select vehicle type"
      >
        <option value="">Select a vehicle type</option>
      </select>
    </>
  );
};

export default VehicleType;
