/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NameInput from "./NameInput";
import TimeInput from "./TimeInput";
import CommuteDays from "./CommuteDays";

const WelcomeForm = () => {
  return (
    <main className="flex flex-col ml-5 w-[64%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col items-start self-stretch my-auto w-full max-md:mt-10 max-md:max-w-full">
        <h1 className="text-6xl font-bold text-center text-gray-900 max-md:text-4xl">
          Welcome
        </h1>
        <p className="mt-10 text-3xl font-medium text-neutral-400 text-opacity-80 max-md:mt-10 max-md:max-w-full">
          Hello! You need to register to enter.
        </p>
        <form>
          <NameInput />
          <div className="self-stretch mt-16 max-md:mt-10 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col">
              <TimeInput label="Start Time" />
              <TimeInput label="End Time" />
            </div>
          </div>
          <CommuteDays />
        </form>
      </div>
    </main>
  );
};

export default WelcomeForm;
